server:
  port: 8763
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          search-paths: config
          uri: https://github.com/kanggeaiphp/ispringcloud.git
          username: kanggeaiphp@163.com
          password: Github123456.
          force-pull: true
          clone-on-start: true
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
